# Generated by Django 4.1.6 on 2023-03-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pwds',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=25)),
                ('field', models.CharField(max_length=25)),
                ('pwd', models.CharField(max_length=60)),
            ],
        ),
    ]
