# Generated by Django 4.1.6 on 2023-03-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safepwds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwds',
            name='pwd',
            field=models.CharField(max_length=200),
        ),
    ]
