# Generated by Django 4.1.6 on 2023-03-13 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safepwds', '0002_alter_pwds_pwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pwds',
            name='pwd',
            field=models.BinaryField(max_length=200),
        ),
    ]
